---
# tasks file for ansible-role-ohpc-finish

- name: check current kernel version
  command: uname -r
  register: running_kernel_version
  changed_when: false

- name: Create WW bootstrap image
  shell: wwbootstrap "{{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }}"

- name: Import ww files
  command: wwsh file import {{ item }}
  with_items: "{{ ohpc_ww_file_import }}"

- name: Create the WW vnfs images
  command: wwvnfs -y --chroot "{{ item }}"
  with_items: "{{ groups.ohpc_images }}"

- name: add node to ww db if it does not already exist
  shell: wwsh node list {{ item }} >/dev/null || wwsh -y node new {{ item }} --ipaddr={{ hostvars[item]['int_ip_addr'] }} --hwaddr={{ hostvars[item]['mac_address'] }} -D {{ hostvars[item]['internal_interface'] }} --netmask={{ hostvars[item]['int_net_mask'] }} --gateway={{ hostvars[item]['int_gateway'] }}
  with_items: "{{ groups.ohpc_compute }}"

- name: Setup ib0
  command: wwsh -y node set {{ item }} -D ib0 --ipaddr={{ hostvars[item]['ib_ip_addr'] }} --netmask={{ hostvars[item]['ib_net_mask'] }}
  with_items: "{{ groups.ohpc_compute }}"
  when: hostvars[item]['ib_ip_addr'] is defined

# TODO: how to set vnfs image???
- name: set files to provision
  command: wwsh -y provision set {{ item }} --vnfs=compute --bootstrap={{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }} --files={{','.join(ohpc_ww_file_import) }} --console=ttyS0,115200  --kargs="selinux=0 net.ifnames=1" --postnetdown=1
  with_items: "{{ groups.ohpc_compute }}"

- name: wwsh pxe update
  command: wwsh pxe update

- name: wwsh dhcp update
  command: wwsh dhcp update

- name: restart dhcpd
  service: name=dhcpd state=restarted enabled=yes
