---
# tasks file for ansible-role-ohpc-finish

- name: check current kernel version
  command: uname -r
  register: running_kernel_version
  changed_when: false

- name: Create WW bootstrap image
  shell: wwbootstrap "{{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }}"

- name: Import ww files
  command: wwsh file import {{ item }}
  with_items: "{{ ohpc_ww_file_import }}"

- name: Create the WW vnfs images
  command: wwvnfs -y --chroot "{{ item }}"
  with_items: "{{ groups.ohpc_images }}"

- name: add node to ww db if it doesn't already exist
  shell: wwsh node list {{ item }} >/dev/null || wwsh -y node new {{ item }} --ipaddr={{ hostvars[item]['int_ip_addr'] }} --hwaddr={{ hostvars[item]['mac_address'] }} -D {{ hostvars[item]['internal_interface'] }}
  with_items: "{{ groups.compute }}"

# TODO: how to set vnfs image???
- name: set files to provision
  command: wwsh -y provision set {{ item }} --vnfs=compute --bootstrap={{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }} --files={{','.join(ohpc_ww_file_import) }}
  with_items: "{{ groups.compute }}"

- name: wwsh pxe update
  command: wwsh pxe update

- name: wwsh dhcp update
  command: wwsh dhcp update

- name: restart dhcpd
  service: name=dhcpd state=restarted
