---
# tasks file for ansible-role-ohpc-provision

- name: check current kernel version
  command: uname -r
  register: running_kernel_version
  changed_when: false

- name: Create WW bootstrap image
  shell: wwbootstrap "{{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }}"

- name: Import ww files
  command: wwsh -y file import {{ item }}
  loop: "{{ ohpc_ww_file_import }}"

- name: Install ifcfg-ib0
  command: wwsh -y file set ifcfg-ib0.ww --path=/etc/sysconfig/network-scripts/ifcfg-ib0

- name: Template script to install the FGCI SSH host keys
  template:
    src: install-fgci-ssh-host-keys.sh.j2
    dest: "{{ item }}/usr/local/sbin/install-fgci-ssh-host-keys.sh"
    mode: 0700
    owner: root
    group: root
  loop: "{{ groups.ohpc_images }}"

- name: Install systemd unit file for FGCI ssh host key script
  copy:
    src: install-fgci-ssh-host-keys.service
    dest: "{{ item }}/etc/systemd/system/install-fgci-ssh-host-keys.service"
    mode: 0664
    owner: root
    group: root
  loop: "{{ groups.ohpc_images }}"

- name: Enable FGCI SSH host key unit
  command: "systemd-nspawn -D {{ item }} systemctl enable install-fgci-ssh-host-keys"
  loop: "{{ groups.ohpc_images }}"

- name: Copy the fix-nhc.py script
  copy:
    src: fix-nhc.py
    dest: "{{ item }}/usr/local/sbin/fix-nhc.py"
    mode: 0700
    owner: root
    group: root
  loop: "{{ groups.ohpc_images }}"

- name: Install systemd unit file for fix-nhc script
  copy:
    src: fix-nhc.service
    dest: "{{ item }}/etc/systemd/system/fix-nhc.service"
    mode: 0664
    owner: root
    group: root
  loop: "{{ groups.ohpc_images }}"

- name: Enable fix-nhc unit
  command: "systemd-nspawn -D {{ item }} systemctl enable fix-nhc"
  loop: "{{ groups.ohpc_images }}"

- name: If network is not up, start it (some race condition on Cascade Lake nodes with i40e driver)
  lineinfile:
    path: "{{ item }}/etc/rc.d/rc.local"
    line: 'if ! systemctl status network > /dev/null; then systemctl start network; fi'
  loop: "{{ groups.ohpc_images }}"

- name: Make sure rc.local is executable
  file:
    path: "{{ item }}/etc/rc.d/rc.local"
    mode: 0744
  loop: "{{ groups.ohpc_images }}"

- name: Create the WW vnfs images
  command: wwvnfs --chroot "{{ item }}"
  loop: "{{ groups.ohpc_images }}"

- name: add node to ww db if it does not already exist
  shell: wwsh node list {{ item }} >/dev/null || wwsh -y node new {{ item }} --ipaddr={{ hostvars[item]['int_ip_addr'] }} --hwaddr={{ hostvars[item]['mac_address'] }} -D {{ hostvars[item]['internal_interface'] }} --netmask={{ hostvars[item]['int_net_mask'] }} --gateway={{ hostvars[item]['int_gateway'] }} --domain={{ dhcp_common_domain }}
  loop: "{{ groups.ohpc_compute }}"

- name: Setup ib0
  command: wwsh -y node set {{ item }} -D ib0 --ipaddr={{ hostvars[item]['ib_ip_addr'] }} --netmask={{ hostvars[item]['ib_net_mask'] }}
  loop: "{{ groups.ohpc_compute }}"
  when: hostvars[item]['ib_ip_addr'] is defined

- name: set files to provision
  command: wwsh -y provision set {{ item }} --vnfs={{ hostvars[item]['ohpc_image'] }} --bootstrap={{ ohpc_build_kernel_ver | default(running_kernel_version.stdout) }} --files={{ ohpc_ww_file_import | map('basename') | list | join(',') }} --console=ttyS0,115200  --kargs="selinux=0 net.ifnames=1 spectre_v2=retpoline" --postnetdown=1
  loop: "{{ groups.ohpc_compute }}"

- name: Setup local disk for stateful nodes
  command: wwsh -y provision set --bootloader=sda --filesystem={{ hostvars[item]['filesystem'] }} {{ item }}
  when: hostvars[item]['filesystem'] is defined
  loop: "{{ groups.ohpc_compute }}"

- name: wwsh pxe update
  command: wwsh pxe update

- name: wwsh dhcp update
  command: wwsh dhcp update

- name: restart dhcpd
  service: name=dhcpd state=restarted enabled=yes
